version: '3.7'
services:
  mercado-libre-api:
    image: mercado-libre-api
    container_name: "mercado-libre-api"
    depends_on:
      - postgres
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
  postgres:
    image: postgres:10.3
    container_name: "mercado-libre-postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5313:5432'
volumes:
  postgres:
